services:
  # MySQL Database
  - type: pserv
    name: shifttrackpro-db
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.mysql
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: shifttrackpro
      - key: MYSQL_USER
        value: shifttrack
      - key: MYSQL_PASSWORD
        generateValue: true

  # Backend API
  - type: web
    name: shifttrackpro-api
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromService:
          type: pserv
          name: shifttrackpro-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        value: shifttrack
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: shifttrackpro-db
          envVarKey: MYSQL_PASSWORD
      - key: DB_DATABASE
        value: shifttrackpro
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h

  # Frontend
  - type: web
    name: shifttrackpro-frontend
    env: static
    region: oregon
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: shifttrackpro-api
          envVarKey: RENDER_EXTERNAL_URL

  # phpMyAdmin (optional)
  - type: web
    name: shifttrackpro-phpmyadmin
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.phpmyadmin
    dockerContext: .
    envVars:
      - key: PMA_HOST
        fromService:
          type: pserv
          name: shifttrackpro-db
          property: host
      - key: PMA_PORT
        value: 3306
      - key: PMA_USER
        value: shifttrack
      - key: PMA_PASSWORD
        fromService:
          type: pserv
          name: shifttrackpro-db
          envVarKey: MYSQL_PASSWORD
      - key: UPLOAD_LIMIT
        value: 50M
